version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000 # Update if backend runs on a different service URL
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true
